spring:
  application:
    name: gateway-zuul

# Expose Eureka via 'registry' context
zuul:
  routes:
    registry:
      url: http://localhost:18765

server:
  port: 8080

eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:18765/eureka

# Explicit list of services which can join the number cloud. Rather for demonstration purposes so far.
whitelist:
  servicesNames:
    - delta # internal Eureka call
    - number-generator
    - primes
    - fibonacci

# Change to 'true' to enable requests and other types of possibly useful logging in the future.
useLoggingFilter: false
